import { Category } from "@/types";

export const CATEGORIES: Category[] = [
  {
    id: "cat-fashion",
    name: "Fashion",
    slug: "fashion",
    description: "Tailored luxury essentials, streetwear, and contemporary silhouettes.",
    image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&auto=format&fit=crop&q=80",
    productCount: 48,
  },
  {
    id: "cat-electronics",
    name: "Electronics",
    slug: "electronics",
    description: "High-fidelity acoustics, studio gear, and minimal computational tools.",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80",
    productCount: 36,
  },
  {
    id: "cat-beauty",
    name: "Beauty",
    slug: "beauty",
    description: "Botanical extracts, active skincare serums, and dermatological rituals.",
    image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&auto=format&fit=crop&q=80",
    productCount: 29,
  },
  {
    id: "cat-home",
    name: "Home",
    slug: "home",
    description: "Architectural objects, artisanal ceramic drinkware, and ambient living.",
    image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80",
    productCount: 42,
  },
  {
    id: "cat-shoes",
    name: "Shoes",
    slug: "shoes",
    description: "Performance trainers, hand-stitched leather loafers, and sleek soles.",
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&auto=format&fit=crop&q=80",
    productCount: 31,
  },
  {
    id: "cat-bags",
    name: "Bags",
    slug: "bags",
    description: "Full-grain calfskin totes, weatherproof weekenders, and compact crossbodies.",
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&auto=format&fit=crop&q=80",
    productCount: 24,
  },
  {
    id: "cat-accessories",
    name: "Accessories",
    slug: "accessories",
    description: "Sterling silver jewelry, handcrafted acetate eyewear, and wallets.",
    image: "https://images.unsplash.com/photo-1511556532299-8f662fc26c06?w=800&auto=format&fit=crop&q=80",
    productCount: 38,
  },
  {
    id: "cat-watches",
    name: "Watches",
    slug: "watches",
    description: "Automatic chronographs, sapphire crystal dials, and minimalist timepieces.",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80",
    productCount: 19,
  },
  {
    id: "cat-sports",
    name: "Sports",
    slug: "sports",
    description: "Thermal compression layers, hydration vessels, and active training gear.",
    image: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80",
    productCount: 22,
  },
  {
    id: "cat-lifestyle",
    name: "Lifestyle",
    slug: "lifestyle",
    description: "Poured amber soy candles, specialty pour-over brewers, and stationery.",
    image: "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=800&auto=format&fit=crop&q=80",
    productCount: 27,
  },
];
